/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API de Usuários
 * OpenAPI spec version: 1.0.0
 */

export type GetUsers200Item = {
  id?: string
  /** @minLength 3 */
  nome: string
  email: string
  createdAt?: string
}
