/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API de Usuários
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Create a new user
 */
export const createUserBodyNomeMin = 3

export const createUserBody = zod.object({
  id: zod.string().optional(),
  nome: zod.string().min(createUserBodyNomeMin),
  email: zod.string().email(),
  createdAt: zod.string().datetime().optional(),
})

/**
 * Get all users
 */
export const getUsersResponseNomeMin = 3

export const getUsersResponseItem = zod.object({
  id: zod.string().optional(),
  nome: zod.string().min(getUsersResponseNomeMin),
  email: zod.string().email(),
  createdAt: zod.string().datetime().optional(),
})
export const getUsersResponse = zod.array(getUsersResponseItem)

/**
 * Update a user
 */
export const updateUserParams = zod.object({
  id: zod.string(),
})

export const updateUserBodyNomeMin = 3

export const updateUserBody = zod.object({
  id: zod.string().optional(),
  nome: zod.string().min(updateUserBodyNomeMin),
  email: zod.string().email(),
  createdAt: zod.string().datetime().optional(),
})

/**
 * Delete a user
 */
export const deleteUserParams = zod.object({
  id: zod.string(),
})
